export const ELEMENTOS_CADASTRO = {
    inputPrimeiroNome: 'input[name="firstName"]',
    inputSobrenome: 'input[name="lastName"]',
    inputEmail: 'input[name="email"]',
    inputSenha: 'input[name="password"]',
    inputConfirmacaoSenha: 'input[id="confirmPassword-field"]',
    inputCpf: 'input[name="cpf"]',
    inputDataNascimento: 'input[name="dateOfBirth"]',
    inputClick: 'input[class="natds185"]',
    inputNumeroCelular: 'input[name="homePhone"]',
    inputNumeroWhatsapp: 'input[name="whatsappPhone"]',
    inputGenero: 'input[name="gender"]',
    inputQueroReceberViaSMS: 'input[id="receiveNewsLetterSms"]',
    inputQueroReceberViaWhatsapp: 'input[id="pushOptInWP"]',
    inputFornecerMinhasInformacoes: 'input[id="infContOptIn"]',
    inputConfirmarMaisDe18Anos: 'input[id="acceptedterms"]',
    inputCriarConta: 'button[class*="MuiButtonBase-root MuiButton-root"]',
};
