trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm init -y
  displayName: 'npm init -y'

  - script: npm install --yes
    displayName: "npm install --yes"

  - script: npm install cypress@12.17.4 -d
    displayName: "Install Cypress"

  - script: npx cypress run --config video=true
    displayName: "Execute Cypress"

  - task: PublishTestResults@1
    displayName: "Publish Test Results"
    condition: succeededOrFailed()
    inputs:
      targetPath: "**/cypress/videos/*.mp4"
      artifactName: "Cypress Videos"
      publishlocation: "pipeline"
