trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm i faker-br --dev
  displayName: 'Instalar dependências'

- script: |
    npx cypress run --config video=true --browser chrome --record --key fb63c5ef-99a6-4271-97c5-ff72917fac41
  displayName: 'Cypress'


  - task: PublishTestResults@1
    displayName: "Publish Test Results"
    condition: succeededOrFailed()
    inputs:
      targetPath: "**/cypress/videos"
      artifactName: "Cypress Videos"
      publishlocation: "pipeline"
